//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLAdding.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class botanical
    {
        public int common_id { get; set; }
        public int botanical_id { get; set; }
        public string botanical_name { get; set; }
        public Nullable<int> light_id { get; set; }
        public Nullable<int> price_id { get; set; }
        public Nullable<int> availability { get; set; }
        public string zone { get; set; }
    
        public virtual common common { get; set; }
        public virtual light light { get; set; }
        public virtual price price { get; set; }
    }
}
